### ISSUE TITLE
Add voice over

### ISSUE THREAD

**Issue by Hiroreco** [Matriz88/hef-website#12]
- Add an option to play audio on designated pages.
- There can be two approaches to this:
1. Have a button that when pressed, plays the audio of the current page (could maybe add a "voice over" checkbox that if checked will play the audio every time the user swaps to a different page).
2. Have  interactable parts on a page that when clicked, plays the corresponding audio (a bit harder to do, also has to consider the fact that page navigation is done through clicking on the page).

**Comment by Pyreko** [comment]
As per discussion on Discord we're not doing this anymore due to time constraints :pensive:
