### ISSUE TITLE
Add scroll to fit width/height

### ISSUE THREAD

**Issue by Pyreko** [Matriz88/hef-website#18]
These need to be scrollable. For example, if you do fit height on a vertical monitor, it will be cut off, so we need to be able to scroll horizontally:

![image](https://github.com/Matriz88/hef-website/assets/25498386/72e027fe-3110-400c-846a-808658665de5)

Ditto for fit width on a horizontal monitor, we need to be able to scroll vertically:

![image](https://github.com/Matriz88/hef-website/assets/25498386/78046ab3-5efe-416b-b7b9-1ce256c5b347)

**Comment by Pyreko** [comment]
Note: I'm pretty sure this broke because I set `height` in `Image`, let me fix that...

**Comment by Hiroreco** [comment]
> Note: I'm pretty sure this broke because I set `height` in `Image`, let me fix that...

Actually, might be a fault on my end. Setting the height and width for a `next/image` doesn’t actually mean the image will be displayed in that dimension (for remote images that is)
![image](https://github.com/Matriz88/hef-website/assets/61302586/0bca33f9-1f2f-49b6-b43b-6a05b46c78d5)
I’ll rewrite the fit modes entirely since it’s kinda confusing rn

**Comment by LegendAVRS** [comment]
For some reason, if we want to do fit height (the one that'll give a horizontal scrollbar on vertical screens), it works fine with the dummy manga. However, it breaks when we try the actual manga. I think it has something to do with how unnecessarily big the dimensions of these pages are, so maybe until we use the optimized images (or make them smaller later), we'll just stick with "object-contain" for now.

### Actual manga
![image](https://github.com/Matriz88/hef-website/assets/61302586/afc84f25-0f5f-490c-8eaa-86d710c0d3fa)

### Dummy manga (is scrollable)
![image](https://github.com/Matriz88/hef-website/assets/61302586/74226eef-eabe-4d12-bbc7-4a8cf5d82341)

### Using object-contain (for now)
![image](https://github.com/Matriz88/hef-website/assets/61302586/28a20718-21df-4c2b-972f-093412456bd9)
