### ISSUE TITLE
Designing Irys's theme / Decorating the reader

### ISSUE THREAD

**Issue by Hiroreco** [Matriz88/hef-website#2]
### Design an Irys theme 
- Color scheme: both light and dark modes should be available.
- Decorate the modal: maybe with lien's chibi irys, stars, animated backgrounds (see link for reference). 
- Decorate the sidebar and header: with stars and stuff (idk that's all i can come up with).
**Reference for decorating:** [https://tokinosora-fc.com/](url)

**Comment by GoldElysium** [comment]
I'll just assign this to myself right now, but will actually look at it in a week or so.
