### ISSUE TITLE
Progress bar tooltips don't follow theme

### ISSUE THREAD

**Issue by Pyreko** [Matriz88/hef-website#32]
I think these are the native tooltips? But they don't follow theme, which might be jarring:

![image](https://github.com/Matriz88/hef-website/assets/25498386/1e7ef807-2423-4111-bd45-e0c140d14418)

Note: this is _super_ minor, feel free to prioritize this later if at all.

**Comment by Hiroreco** [comment]
Done in [4852353](https://github.com/Matriz88/hef-website/commit/485235358c0e12f7054ba8d272a177c21554d917)
![image](https://github.com/Matriz88/hef-website/assets/61302586/6ffec6cf-72ef-4a18-bd0e-f3ca613e168a)
![image](https://github.com/Matriz88/hef-website/assets/61302586/43918d29-b612-46ca-b4c2-82cb95c1bbf1)
