### ISSUE TITLE
Should we combine long strip and LTR/RTL?

### ISSUE THREAD

**Issue by Pyreko** [Matriz88/hef-website#35]
Having them as separate settings is... weird IMO, as what is supposed to happen if you have LTR and long strip set?

MD keeps them separate, for example (where ltr/rtl mainly just controls which side controls page increment/decrement), while sites like guya or phone readers generally don't from what I noticed.

**Comment by Hiroreco** [comment]
Sure! I also think it makes more sense that way

**Comment by Hiroreco** [comment]
Done in [#e2a88b2](https://github.com/Matriz88/hef-website/commit/e2a88b22a2fda94a16bc5a4cd4a4d44f4e04d780)
![image](https://github.com/Matriz88/hef-website/assets/61302586/b636624d-91bd-4593-9f8f-8a10c5ed4ecb)
![image](https://github.com/Matriz88/hef-website/assets/61302586/05478aaf-13b4-4cd4-be8c-f5c41fb83f0b)
![image](https://github.com/Matriz88/hef-website/assets/61302586/0934007a-cc04-45db-9668-7f42069b68b2)
