### ISSUE TITLE
Handle image load

### ISSUE THREAD

**Issue by Hiroreco** [Matriz88/hef-website#5]
Add some kind of **loading indicator** when waiting for the pages to be fetched. Moreover, add **lazyload** to the images.
_Loading indicator example:_
![image](https://github.com/Matriz88/hef-website/assets/61302586/527a7128-a5db-4d03-b28f-b17ea045863d)

**Comment by Pyreko** [comment]
Lazy loading part done in #9.

**Comment by Hiroreco** [comment]
Added loading icon in [f4fce58](https://github.com/Matriz88/hef-website/commit/f4fce58aab6e48b7fa01a09435818e74a8448984)
