### ISSUE TITLE
Fit mode breaks when turning screen

### ISSUE THREAD

**Issue by Hiroreco** [Matriz88/hef-website#51]
Probably just need to recalculate the dimensions whenever the user turns

https://github.com/Matriz88/hef-website/assets/61302586/a3298db8-30b9-4b93-b1ed-e3991e1c3827

**Comment by Pyreko** [comment]
Uhhh... so I can't reproduce this lol

**Comment by Hiroreco** [comment]
Closing cause apparently it's a skill issue
